<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>SuchArt_VR</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Deploy to local folder mirroring game structure -->
  <Target Name="DeployToFolder" AfterTargets="Build">
    <!-- Create directories in deploy folder -->
    <MakeDir Directories="$(MSBuildThisFileDirectory)deploy\SuchArt\BepInEx\plugins\SuchArt VR" />
    <MakeDir Directories="$(MSBuildThisFileDirectory)deploy\SuchArt\SuchArt_Data\Managed" />
    <MakeDir Directories="$(MSBuildThisFileDirectory)deploy\SuchArt\SuchArt_Data\Plugins" />
    <MakeDir Directories="$(MSBuildThisFileDirectory)deploy\SuchArt\SuchArt_Data\StreamingAssets" />
    <MakeDir Directories="$(MSBuildThisFileDirectory)deploy\SuchArt\SuchArt_Data\UnitySubsystems" />
    
    <!-- Main plugin DLL to BepInEx/plugins -->
    <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll" DestinationFolder="$(MSBuildThisFileDirectory)deploy\SuchArt\BepInEx\plugins\SuchArt VR" />
    
    <!-- Libs DLLs to SuchArt_Data/Managed -->
    <Copy SourceFiles="@(LibsDlls)" DestinationFolder="$(MSBuildThisFileDirectory)deploy\SuchArt\SuchArt_Data\Managed\" />
    
    <!-- Native plugins to SuchArt_Data/Plugins -->
    <Copy SourceFiles="@(LibsPlugins)" DestinationFolder="$(MSBuildThisFileDirectory)deploy\SuchArt\SuchArt_Data\Plugins\" />
    
    <!-- StreamingAssets -->
    <Copy SourceFiles="@(LibsStreamingAssets)" DestinationFolder="$(MSBuildThisFileDirectory)deploy\SuchArt\SuchArt_Data\StreamingAssets\%(RecursiveDir)" />
    
    <!-- UnitySubsystems -->
    <Copy SourceFiles="@(LibsSubsystems)" DestinationFolder="$(MSBuildThisFileDirectory)deploy\SuchArt\SuchArt_Data\UnitySubsystems\%(RecursiveDir)" />
  </Target>

  <!-- ItemGroups for Libs files to deploy -->
  <ItemGroup>
    <LibsDlls Include="$(MSBuildThisFileDirectory)..\Libs\Managed\*.dll" />
    <LibsPlugins Include="$(MSBuildThisFileDirectory)..\Libs\Plugins\*.*" />
    <LibsStreamingAssets Include="$(MSBuildThisFileDirectory)..\Libs\StreamingAssets\**\*.*" />
    <LibsSubsystems Include="$(MSBuildThisFileDirectory)..\Libs\UnitySubsystems\**\*.*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="HarmonyX" Version="2.16.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="SteamVR">
      <HintPath>..\Libs\Managed\SteamVR.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="SteamVR_Actions">
      <HintPath>..\Libs\Managed\SteamVR_Actions.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Unity.AI.Navigation">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.AI.Navigation.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Analytics.DataPrivacy">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.Analytics.DataPrivacy.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem.ForUI">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.InputSystem.ForUI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Analytics">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.Services.Analytics.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.Services.Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Analytics">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.Services.Core.Analytics.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Configuration">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.Services.Core.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Device">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.Services.Core.Device.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Environments">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.Services.Core.Environments.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Environments.Internal">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.Services.Core.Environments.Internal.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Internal">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.Services.Core.Internal.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Networking">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.Services.Core.Networking.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Registration">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.Services.Core.Registration.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Scheduler">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.Services.Core.Scheduler.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Telemetry">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.Services.Core.Telemetry.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Threading">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.Services.Core.Threading.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Timeline">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\Unity.Timeline.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.CoreUtils">
      <HintPath>..\Libs\Managed\Unity.XR.CoreUtils.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.Management">
      <HintPath>..\Libs\Managed\Unity.XR.Management.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.OpenVR">
      <HintPath>..\Libs\Managed\Unity.XR.OpenVR.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.OpenXR">
      <HintPath>..\Libs\Managed\Unity.XR.OpenXR.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.OpenXR.Features.ConformanceAutomation">
      <HintPath>..\Libs\Managed\Unity.XR.OpenXR.Features.ConformanceAutomation.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.OpenXR.Features.MetaQuestSupport">
      <HintPath>..\Libs\Managed\Unity.XR.OpenXR.Features.MetaQuestSupport.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.OpenXR.Features.MockRuntime">
      <HintPath>..\Libs\Managed\Unity.XR.OpenXR.Features.MockRuntime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.OpenXR.Features.OculusQuestSupport">
      <HintPath>..\Libs\Managed\Unity.XR.OpenXR.Features.OculusQuestSupport.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.OpenXR.Features.RuntimeDebugger">
      <HintPath>..\Libs\Managed\Unity.XR.OpenXR.Features.RuntimeDebugger.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AccessibilityModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.AccessibilityModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Advertisements">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.Advertisements.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.AIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AndroidJNIModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.AndroidJNIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ARModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.ARModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClothModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.ClothModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClusterInputModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.ClusterInputModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClusterRendererModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.ClusterRendererModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ContentLoadModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.ContentLoadModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CrashReportingModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.CrashReportingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.DirectorModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.DirectorModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.DSPGraphModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.DSPGraphModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GameCenterModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.GameCenterModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GIModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.GIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GridModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.GridModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.HotReloadModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.HotReloadModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.InputModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.LocalizationModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.LocalizationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Monetization">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.Monetization.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.NVIDIAModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.NVIDIAModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PerformanceReportingModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.PerformanceReportingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ProfilerModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.ProfilerModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PropertiesModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.PropertiesModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.Purchasing.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.AppleCore">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.Purchasing.AppleCore.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.AppleMacosStub">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.Purchasing.AppleMacosStub.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.AppleStub">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.Purchasing.AppleStub.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.Codeless">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.Purchasing.Codeless.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.SecurityCore">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.Purchasing.SecurityCore.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.SecurityStub">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.Purchasing.SecurityStub.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.Stores">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.Purchasing.Stores.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.WinRTCore">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.Purchasing.WinRTCore.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.WinRTStub">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.Purchasing.WinRTStub.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.ScreenCaptureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SharedInternalsModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.SharedInternalsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpatialTracking">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.SpatialTracking.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpriteMaskModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.SpriteMaskModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpriteShapeModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.SpriteShapeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.StreamingModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.StreamingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SubstanceModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.SubstanceModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SubsystemsModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.SubsystemsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.TerrainModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainPhysicsModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.TerrainPhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.TextCoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreTextEngineModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TilemapModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.TilemapModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TLSModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.TLSModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsNativeModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.UIElementsNativeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UmbraModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.UmbraModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UNETModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.UNETModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.UnityAnalyticsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityConnectModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.UnityConnectModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityCurlModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.UnityCurlModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityTestProtocolModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.UnityTestProtocolModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAudioModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestTextureModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestWWWModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VehiclesModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.VehiclesModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VFXModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.VFXModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VirtualTexturingModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.VirtualTexturingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VRModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.VRModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.WindModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.WindModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.XR.LegacyInputHelpers">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.XR.LegacyInputHelpers.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.XRModule">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityEngine.XRModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityUIExtensions">
      <HintPath>E:\SteamLibrary\steamapps\common\SuchArt\SuchArt_Data\Managed\UnityUIExtensions.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
